org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-sophisticated
addon_name=BlueMap Sophisticated Add-on
addon_version=0.1.0-alpha.3
addon_group=io.github.jan-guenter
artifact_id=bluemap-sophisticated-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=118181
accepted_jar_sha256=c91ae67275be1bb2e343170b4f800420721c128bed8292b24c4432d65ebdb1ca
accepted_sources_jar_size=76764
accepted_sources_jar_sha256=c20d558efe8365a64b2f5d639a263b02ffac8dc9121629ea31f433eff2338d3f
accepted_pom_size=1375
accepted_pom_sha256=9958e23b10869253db8bf859b66f9c96d4ecc61bda04e6f2239240498ce5d90a
accepted_module_size=2861
accepted_module_sha256=c148e90025bb34a03b7d5633decef3cdc6e4b0753e41dc692a7db36b15aef98e
