org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-sophisticated
addon_name=BlueMap Sophisticated Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-sophisticated-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=116914
accepted_jar_sha256=8d434eff624a831ac1327e9b17347fa6b4325c02a001be418fe6593b6c300dab
accepted_sources_jar_size=75490
accepted_sources_jar_sha256=02985e6012cb640104bc2eae2211037a4a1977fcc4a9d54c59e29886d9c737f9
accepted_pom_size=1375
accepted_pom_sha256=eb038746fa5cbb8807e7b5781257930475e09508c54470e29b9679f562afcd97
accepted_module_size=2861
accepted_module_sha256=19ffadce6d84514ae0609cc2298345509612dfa426bdd170e3e6506d9490411b
